port: "8080"

db:
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  dbName: "L0"
 #postgres://username:password@host:port/database_name

stanClusterID: "wbCluster"
stanClientID: "wbSubscribe"
subscriberDurableName: "name"
channelName: "orderChannel"